export const types = Object.freeze({
  // Sync
  START_FETCHING: '[FORECAST] - START_FETCHING',
  STOP_FETCHING: '[FORECAST] - STOP_FETCHING',
  DAYS_FILL: '[FORECAST] - DAYS_FILL',
  DAY_FILL: '[FORECAST] - DAY_FILL',
  SET_FETCHING_ERROR: '[FORECAST] - SET_FETCHING_ERROR',
  SET_FILTER: '[FORECAST] - SET_FILTER',
  CLEAR_FILTER: '[FORECAST] - CLEAR_FILTER',

  //Async
  FORECAST_FETCH_ASYNC: '[FORECAST] - FORECAST_FETCH_ASYNC',

})
