export const types = Object.freeze({
  // Sync
  START_FETCHING: '[TODO] - START_FETCHING',
  STOP_FETCHING: '[TODO] - STOP_FETCHING',
  TASKS_FILL: '[TODO] - TASKS_FILL',
  TASK_FILL: '[TODO] - TASK_FILL',
  SET_FETCHING_ERROR: '[TODO] - SET_FETCHING_ERROR',
  TASK_CHANGE_STATUS: '[TODO] - TASK_CHANGE_STATUS',

  //Async
  GET_TASKS_ASYNC: '[TODO] - GET_TASKS_ASYNC',
  GET_TASK_ASYNC: '[TODO] - GET_TASK_ASYNC',
  CREATE_TASK_ASYNC: '[TODO] - CREATE_TASK_ASYNC',
  UPDATE_TASK_ASYNC: '[TODO] - UPDATE_TASK_ASYNC',
  DELETE_TASK_ASYNC: '[TODO] - DELETE_TASK_ASYNC',

})
